from enum import Enum


class Bacteria(Enum):
    MYCOBACTERIUM_TUBERCULOSIS = "mycobacterium_tuberculosis"
    PSEUDOMONAS_AUREGINOSA = "pseudomonas_aureginosa"
    GENOME_MIX = "genome_mix"
    GENOME_MIX_NEW = "genome_mix_new"
    TEST = "test"


class ProcessingMode(Enum):
    NON_OVERLAPPING = "non_overlapping"
    OVERLAPPING = "overlapping"


class TestMethod(Enum):
    CV = "cv"
    TRAIN_TEST = "train_test"


class AggregationMethod(Enum):
    EMBEDDINGS = "embeddings"
    SCORES = "scores"


class ClassifierType(Enum):
    XGBOOST = "xgboost"
    KNN = "knn"


# antibiotic dic
ANTIBIOTIC_DIC = {
    # Bacteria.PSEUDOMONAS_AUREGINOSA.value: ['imipenem', 'ceftazidime', 'meropenem', 'levofloxacin', 'amikacin'],
    Bacteria.PSEUDOMONAS_AUREGINOSA.value: ['imipenem'],
    Bacteria.MYCOBACTERIUM_TUBERCULOSIS.value: ['isoniazid', 'ethambutol', 'rifampin', 'streptomycin', 'pyrazinamide'],
    Bacteria.TEST.value: ['amikacin', 'levofloxacin', 'meropenem', 'ceftazidime', 'imipenem'],
}

EMBEDDING_DF_FILE_NAME = "embedding_df.h5"
METADATA_DF_FILE_NAME = "metadata_df.csv"


PREDEFINED_FEATURES_LIST = {
    Bacteria.PSEUDOMONAS_AUREGINOSA.value: {
        "imipenem": ["CGTGCCGCGC", "TGGCCTGCGT", "TCACAGGACA", "TATTGCCCTG", "ACCTACAAGA", "CCAATGTACG", "CCGGCGCGAA", "TTGCCGAAAA", "GAGGTGGCCA", "CCTGTCCGCT", "TTCTCGTTTC", "GCCCTGGATA", "TGATGGAGGC", "CGTCGCTCGC", "TCGCGGGTCA", "CCACGCCACA", "ATGGGTGCGC", "GAGCCGAGTC", "GCCAACGGAC", "GGCAGCTCGG", "TAACCGTTTG", "GGATACTTCC", "TGCGGCGTTT", "TCTACAGCGC", "TTGCTTAACT", "TAAGCACCGC", "CTGAAAGCCC", "TACGGCCCCA", "ATTTCTCTCG", "GATCTCCAGC", "AGAAGCGAAT", "GTCGAAGTCC", "CGTCACCGAC", "GCCGGAACGG", "CCCGTTTAAA", "AGCTGGATGG", "CATGGCCGCT", "AGAAGGAATC", "TACGACTACC", "GATGCGGGCA", "GCCTCATCGA", "GGGGGGGCGG", "TATCGAGATC", "GCCCGCTTGG", "CTACGCCTAT", "GCTACCCCTG", "CTTGTTCCTC", "GGGTGGATGC", "GTCGCTGTAC", "GTCCTCCTCC", "AATCGGTGAC", "GACCTGCCTG", "CGTCGACCGT", "CGCAGTTGCA", "CTCGCCGCAG", "GATGAAGAAG", "TAGACCTGCA", "TCACGCTTCT", "TTCTTCGGCG", "ATAACTAACG", "CCGACAAGGG", "GACGTACGCA", "AGGCCTTTTT", "CCTCGCGCAC", "TGACGCGCCC", "GTGGCCGTGT", "CGCAGCTTTC", "TGGCCAATCG", "GATGGGATTT", "TCGCCCAGCC", "CAACCGCGTC", "CGGTGCCCGG", "GATCGAGACT", "AAACCCGGCG", "ACTGCTGCGA", "TTGTGTTGAG", "GAAGGTGACT", "CGCACGCAAG", "GCTTCCAGGG", "ACGACCACCA", "CTCGTCGGTG", "TGTTCGACAC", "TGGGCGAGCA", "GCGAGAGCTA", "CGGAACGGGC", "CACGGAGCTG", "CAGTGACCTT", "AGAAACGAAT", "AGATTTCTCT", "TCCGGCTCAC", "GTGGCCCGTG", "TGAGGGGAAT", "CCCGCCGGCC", "GATCAGCCAG", "AGCGCGCTGG", "TCGATGCCCG", "CGCCCAGGTG", "GTTTATTATA", "ACTTTGCCCG", "TGGTGCCACT", "GTTGCGCGGA", "GAACTGCTCT", "GAGTGCGCTG", "CTGGCCGCGT", "GTACTGGTCC", "CGCAGCGTGA", "GGTGGCTTTC", "GGAAGGCATC", "AGTTTGGATC", "GCCACGTATT", "ATCGGTGTCC", "GCGAAACCCC", "ACTCGGCATC", "GATGCTCCCT", "CGCAAGGCCG", "CAGTGGGGAC", "TCAAAATCGA", "CTTCTGACGA", "TTCAATGCCA", "CCCGGCCGGC", "GTGGGAATGC", "ACGCAGCGCC", "GCCGACATCG", "CGCCGCAGTC", "TAGGTCAGAG", "GTTTAACTCG", "TGCCCTACAG", "GCTTCCTGCC", "CGCGTTCCAT", "CTGGGTGTTA", "ATCAGTTGGG", "TCCGGTGCGG", "GGATGTGCAG", "CCGGTGAAAG", "ACTCGCCGTT", "AGAACCTGTC", "CACCCACGCC", "AATAGAAGCC", "GGCAGCGAGG", "CTTGCTGCCA", "TTGCCGAAGG", "CTCTTTCATA", "AAACCTGTCG", "GATCAGCGTA", "CCGAGGAGGT", "CATTTGAAGC", "CAGCGAGCCA", "AAAAGCGCAG", "ACAGCCATTC", "CTGCGGCATC", "TCAATGCCAC", "GGCGTAGCCG", "CACAACGCCA", "TAGCGGCGCT", "TACGGGGTCA", "TTGCCGTCCC", "TTCAGCAGCG", "TTTGCCGCCT", "CAAAGGTGGC", "GCCTCTTTTT", "TTCTCCTATT", "AGGCAATCAT", "GAGCGTCATT", "AGGTGCGCCA", "TAACGATCCG", "CGCCGGAGTG", "CAACACCTTG", "GGCCGGCAAT", "CCACGGTGAC", "GCCCCGCCGG", "CCAGACGCGC", "CCTGTGAATA", "GTCTTCTTCG", "GGTCGAGCGG", "CGGCGAGGTT", "GCTCAACTGC", "GCACGTTACC", "TGTGGCAGGA", "AAGGGATCGG", "CGAGACACGG", "ACCACGCGGT", "GCGCCGCAGC", "TGATCGACAG", "ACAGTACGTA", "TCCAGTGGCC", "CTTCTGACAA", "GTTCTTTGAG", "TGAGCACATC", "AGCACCTCGG", "TCTGGTCAAG", "GATCAGGTTC", "TATCCAGTTC", "TCTTTTATGA", "AACTCCTGGC", "CAACGCTGAG", "CGTAAGATCG", "CCATTCCCGA", "CACCAGCAGG", "CCGAATTCAT", "GATGGTCGTA", "ATCGCGGGGT", "TAGCACCGTT", "GGATCAGCGA", "TCCGCCTGAA", "GACCAGTCCA", "CCACTGGTCC", "CGGCTTGACC", "GAGAAAGAAC", "CCATCGATAG", "CGACTCATGC", "GGGTCGCGGA", "CTGCGCAAAT", "ATCACATCGT", "GCATCAACTG", "CTGGCGAATT", "CTAATGATGG", "CCTCCGCAGT", "AGGCGACGGT", "TCGCATAGGT", "CCCGGCATGG", "ATTCCGCACA", "CTCGCGAGCA", "ATCGACAACA", "AACATGGTGG", "CATGACCATG", "GGCTATCGTC", "CAAGCCTTTG", "ATCAGCGAGG", "AGTGTTCTCG", "ACCTGGTGGT", "GCGGACGTAA", "TGTTGATGCA", "TGCGACCACC", "GCACATCCGC", "GCAGCCGGTG", "AGCAGGACCG", "ATCAGTCGAA", "CAGAAGACGG", "CGTCCGCGCG", "AGTCGGTGTA", "AGCCTCTATC", "GCCTATGCAC", "CGGCACGAAC", "TTCGCTGGCG", "GATCGGGCAT", "CCCCATGATG", "TGCCGACAGC", "AATGGCATAA", "CTCAGCACCT", "AGTTGCTGGA", "CGGTCTTGTT", "ACCCCGCGCC", "CAAAGCATAT", "GTGATAGTCC", "CTTCGAGCGT", "TGATCATGGC", "TGACGGGTGC", "TTTCCAACAT", "CCGTTCAACG", "GTAGCTTGGA", "CTGATCCACG", "GAACACCACC", "TCCGGCGGGC", "CGAAGCAGAG", "GCCCGGACGC", "TGGTGACCTC", "GGGTTATATT", "TTTGGCAATC", "CTGGAATTTT", "ATCGATAATC", "TCGATCCGGC", "TCCTGGTACA", "AAGCTGGCCG", "GACGTGCCGC", "GGTAAGCATC", "GTTTGCCCCT", "GCGATTTGCT", "GCTATAGTGC", "ACATGTCCCG", "TCGCCAATTT", "CGCTTTCCCC", "CGAAGGTTCG", "CAGTACATGT", "CGCAGTAGGT", "CAGGCTTGAA", "TAGTTGCAAC", "CAATGGCACC", "GTTGTCTCGC", "TTGGCGAATG", "GTGCGGCCGC", "TTCATCAGAG", "CGGACACCCC", "CAAAGCTTAA", "GTCGTCGACC", "GACAGACCTG", "CTCCGCCTGC", "GGCCGACGGC", "TTCCTCTTTC", "ACAGCAATCA", "CGCGGCGAAG"],
    }
}
